import { Config } from "effect"
import { InstallationChannel } from "../installation/version"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

// Channels that default to the new effect-httpapi server backend. The legacy
// hono backend remains the default for stable (`prod`/`latest`) installs.
const HTTPAPI_DEFAULT_ON_CHANNELS = new Set(["dev", "beta", "local"])

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const LOCALCODER_EXPERIMENTAL = truthy("LOCALCODER_EXPERIMENTAL")
const LOCALCODER_DISABLE_CLAUDE_CODE = truthy("LOCALCODER_DISABLE_CLAUDE_CODE")
const LOCALCODER_DISABLE_CLAUDE_CODE_SKILLS =
  LOCALCODER_DISABLE_CLAUDE_CODE || truthy("LOCALCODER_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["LOCALCODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  LOCALCODER_AUTO_SHARE: truthy("LOCALCODER_AUTO_SHARE"),
  LOCALCODER_AUTO_HEAP_SNAPSHOT: truthy("LOCALCODER_AUTO_HEAP_SNAPSHOT"),
  LOCALCODER_GIT_BASH_PATH: process.env["LOCALCODER_GIT_BASH_PATH"],
  LOCALCODER_CONFIG: process.env["LOCALCODER_CONFIG"],
  LOCALCODER_CONFIG_CONTENT: process.env["LOCALCODER_CONFIG_CONTENT"],
  LOCALCODER_DISABLE_AUTOUPDATE: truthy("LOCALCODER_DISABLE_AUTOUPDATE"),
  LOCALCODER_ALWAYS_NOTIFY_UPDATE: truthy("LOCALCODER_ALWAYS_NOTIFY_UPDATE"),
  LOCALCODER_DISABLE_PRUNE: truthy("LOCALCODER_DISABLE_PRUNE"),
  LOCALCODER_DISABLE_TERMINAL_TITLE: truthy("LOCALCODER_DISABLE_TERMINAL_TITLE"),
  LOCALCODER_SHOW_TTFD: truthy("LOCALCODER_SHOW_TTFD"),
  LOCALCODER_PERMISSION: process.env["LOCALCODER_PERMISSION"],
  LOCALCODER_DISABLE_DEFAULT_PLUGINS: truthy("LOCALCODER_DISABLE_DEFAULT_PLUGINS"),
  LOCALCODER_DISABLE_LSP_DOWNLOAD: truthy("LOCALCODER_DISABLE_LSP_DOWNLOAD"),
  LOCALCODER_ENABLE_EXPERIMENTAL_MODELS: truthy("LOCALCODER_ENABLE_EXPERIMENTAL_MODELS"),
  LOCALCODER_DISABLE_AUTOCOMPACT: truthy("LOCALCODER_DISABLE_AUTOCOMPACT"),
  LOCALCODER_DISABLE_MODELS_FETCH: truthy("LOCALCODER_DISABLE_MODELS_FETCH"),
  LOCALCODER_DISABLE_MOUSE: truthy("LOCALCODER_DISABLE_MOUSE"),
  LOCALCODER_DISABLE_CLAUDE_CODE,
  LOCALCODER_DISABLE_CLAUDE_CODE_PROMPT: LOCALCODER_DISABLE_CLAUDE_CODE || truthy("LOCALCODER_DISABLE_CLAUDE_CODE_PROMPT"),
  LOCALCODER_DISABLE_CLAUDE_CODE_SKILLS,
  LOCALCODER_DISABLE_EXTERNAL_SKILLS: truthy("LOCALCODER_DISABLE_EXTERNAL_SKILLS"),
  LOCALCODER_FAKE_VCS: process.env["LOCALCODER_FAKE_VCS"],
  LOCALCODER_SERVER_PASSWORD: process.env["LOCALCODER_SERVER_PASSWORD"],
  LOCALCODER_SERVER_USERNAME: process.env["LOCALCODER_SERVER_USERNAME"],
  LOCALCODER_ENABLE_QUESTION_TOOL: truthy("LOCALCODER_ENABLE_QUESTION_TOOL"),

  // Experimental
  LOCALCODER_EXPERIMENTAL,
  LOCALCODER_EXPERIMENTAL_FILEWATCHER: Config.boolean("LOCALCODER_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  LOCALCODER_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("LOCALCODER_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  LOCALCODER_EXPERIMENTAL_ICON_DISCOVERY: LOCALCODER_EXPERIMENTAL || truthy("LOCALCODER_EXPERIMENTAL_ICON_DISCOVERY"),
  LOCALCODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("LOCALCODER_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  LOCALCODER_ENABLE_EXA: truthy("LOCALCODER_ENABLE_EXA") || LOCALCODER_EXPERIMENTAL || truthy("LOCALCODER_EXPERIMENTAL_EXA"),
  LOCALCODER_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("LOCALCODER_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  LOCALCODER_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("LOCALCODER_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  LOCALCODER_EXPERIMENTAL_OXFMT: LOCALCODER_EXPERIMENTAL || truthy("LOCALCODER_EXPERIMENTAL_OXFMT"),
  LOCALCODER_EXPERIMENTAL_LSP_TY: truthy("LOCALCODER_EXPERIMENTAL_LSP_TY"),
  LOCALCODER_EXPERIMENTAL_LSP_TOOL: LOCALCODER_EXPERIMENTAL || truthy("LOCALCODER_EXPERIMENTAL_LSP_TOOL"),
  LOCALCODER_EXPERIMENTAL_PLAN_MODE: LOCALCODER_EXPERIMENTAL || truthy("LOCALCODER_EXPERIMENTAL_PLAN_MODE"),
  LOCALCODER_EXPERIMENTAL_MARKDOWN: !falsy("LOCALCODER_EXPERIMENTAL_MARKDOWN"),
  LOCALCODER_MODELS_URL: process.env["LOCALCODER_MODELS_URL"],
  LOCALCODER_MODELS_PATH: process.env["LOCALCODER_MODELS_PATH"],
  LOCALCODER_DISABLE_EMBEDDED_WEB_UI: truthy("LOCALCODER_DISABLE_EMBEDDED_WEB_UI"),
  LOCALCODER_DB: process.env["LOCALCODER_DB"],
  LOCALCODER_DISABLE_CHANNEL_DB: truthy("LOCALCODER_DISABLE_CHANNEL_DB"),
  LOCALCODER_SKIP_MIGRATIONS: truthy("LOCALCODER_SKIP_MIGRATIONS"),
  LOCALCODER_STRICT_CONFIG_DEPS: truthy("LOCALCODER_STRICT_CONFIG_DEPS"),

  LOCALCODER_WORKSPACE_ID: process.env["LOCALCODER_WORKSPACE_ID"],
  // Defaults to true on dev/beta/local channels so internal users exercise the
  // new effect-httpapi server backend. Stable (`prod`/`latest`) installs stay
  // on the legacy hono backend until the rollout is complete. An explicit env
  // var ("true"/"1" or "false"/"0") always wins, providing an opt-in for
  // stable users and an escape hatch for dev/beta users.
  LOCALCODER_EXPERIMENTAL_HTTPAPI:
    truthy("LOCALCODER_EXPERIMENTAL_HTTPAPI") ||
    (!falsy("LOCALCODER_EXPERIMENTAL_HTTPAPI") && HTTPAPI_DEFAULT_ON_CHANNELS.has(InstallationChannel)),
  LOCALCODER_EXPERIMENTAL_WORKSPACES: LOCALCODER_EXPERIMENTAL || truthy("LOCALCODER_EXPERIMENTAL_WORKSPACES"),
  LOCALCODER_EXPERIMENTAL_EVENT_SYSTEM: LOCALCODER_EXPERIMENTAL || truthy("LOCALCODER_EXPERIMENTAL_EVENT_SYSTEM"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get LOCALCODER_DISABLE_PROJECT_CONFIG() {
    return truthy("LOCALCODER_DISABLE_PROJECT_CONFIG")
  },
  get LOCALCODER_TUI_CONFIG() {
    return process.env["LOCALCODER_TUI_CONFIG"]
  },
  get LOCALCODER_CONFIG_DIR() {
    return process.env["LOCALCODER_CONFIG_DIR"]
  },
  get LOCALCODER_PURE() {
    return truthy("LOCALCODER_PURE")
  },
  get LOCALCODER_PLUGIN_META_FILE() {
    return process.env["LOCALCODER_PLUGIN_META_FILE"]
  },
  get LOCALCODER_CLIENT() {
    return process.env["LOCALCODER_CLIENT"] ?? "cli"
  },
}
